package com.dualand.app.activities

import com.dualand.app.R
import com.dualand.app.models.Dua

object DuaDataProvider {
    val duaList = listOf(
        Dua(
            id = 1,
            arabic = "سُبْحَانَ اللّٰہِ وَبِحَمْدِہِ سُبْحَانَ اللّٰہِ الْعَظِیْمِ",
            translation = "Glory be to Allah and all praise be to Him; Glory be to Allah, the Most Great.",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            reference = "[Ṣaḥīḥ Muslim]",
            textheading = " Praise and Glory",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            image = R.drawable.kaaba,
            duaNumber = "1. ",
            fullAudioResId = R.raw.dua01_part01_audio01_complete,
            titleAudioResId = R.raw.title_praise_and_glory,
            wordAudioPairs = listOf(
                "سُبْحَانَ اللّٰہِ" to R.raw.dua01_part01_audio01,
                "وَبِحَمْدِہِ" to R.raw.dua01_part01_audio02,
                "سُبْحَانَ اللّٰہِ الْعَظِیْمِ" to R.raw.dua01_part01_audio03,

                )
        ),
        Dua(
            id = 2,
            arabic = "اَللّٰہُ اَکْبَرُکَبِیْرًاوَّالْحَمْدُ لِلّٰہِ کَثِیْرًاوَّسُبْحَانَ اللّٰہِ بُکْرَةً وَّاَصِیْلًا",
            translation = "Allah is truly Great, praise be to Allah in abundance and glory be to Allah in the morning and the evening.",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            reference = "[Sahih Muslim]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua01_part02_audio01_complete,
            // titleAudioResId = R.raw.title_praise_and_glory,
            image = R.drawable.kaaba,
            duaNumber = "1. ",
           // textheading = "Praise and Glory",
            wordAudioPairs = listOf(
                "اَللّٰہُ اَکْبَرُکَبِیْرًا" to R.raw.dua01_part02_audio01,
                "وَّالْحَمْدُ لِلّٰہِ کَثِیْرًا" to R.raw.dua01_part02_audio02,
                "وَّسُبْحَانَ اللّٰہِ" to R.raw.dua01_part02_audio03,
                "بُکْرَةً وَّاَصِیْلًا۔" to R.raw.dua01_part02_audio04,
            )
        ),
        Dua(
            id = 3,
            arabic = "اَللّٰھُمَّ صَلِّ عَلٰی مُحَمَّدٍ وَّعَلٰی آلِ مُحَمَّدٍ",
            translation = "O Allah! bestow Your mercy upon Mohammad ﷺ and upon the family of Mohammad ﷺ.",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            reference = "[Sunan al-Nasā‘ī]",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua02_part01_audio01_complete,
            titleAudioResId = R.raw.title_peace,
            duaNumber = "2. ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            textheading = "Peace and Blessing upon\n" + "the Prophet Muhammad ﷺ",
            image = R.drawable.dua_2,
            wordAudioPairs = listOf(
                "اَللّٰھُمَّ صَلِّ عَلٰی" to R.raw.dua02_part01_audio01,
                "مُحَمَّدٍ وَّعَلٰی" to R.raw.dua02_part01_audio02,
                "آلِ مُحَمَّدٍ" to R.raw.dua02_part01_audio03,
            )
        ),
        Dua(
            id = 4,
            arabic = "اَللّٰھُمَّ صَلِّ عَلٰی مُحَمَّدٍ عَبْدِکَ وَ رَسُوْلِکَ کَمَا صَلَّیْتَ عَلٰی اِبْرَاھِیْمَ وَ بَارِکْ عَلٰی مُحَمَّدٍ وَّعَلٰی آلِ مُحَمَّدٍ کَمَا بَارَکْتَ عَلٰی اِبْرَاھِیْمَ وَآلِ اِبْرَاھِیْمَ۔",
            translation = "O Allah! Bestow mercy upon your servant and messenger, Mohammad ﷺ, as You bestowed Your mercy upon Ibrahim AS and bless Mohammad ﷺ and the family of Mohammad ﷺ,as You blessed Ibrahim (AS) and the family Ibrahim (AS). ",
            reference = "[Ṣaḥīḥ al-Bukhārī]",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua02_part02_audio01_complete,
            //titleAudioResId = R.raw.title_peace,
            //textheading = "Peace and Blessing upon\n" + "the Prophet Muhammad ﷺ",
            image = R.drawable.dua_2,
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            duaNumber = "2. ",
            wordAudioPairs = listOf(
                "اَللّٰھُمَّ صَلِّ عَلٰی" to R.raw.dua02_part02_audio01,
                "مُحَمَّدٍ عَبْدِکَ" to R.raw.dua02_part02_audio02,
                "وَ رَسُوْلِکَ" to R.raw.dua02_part02_audio03,
                "کَمَا صَلَّیْتَ" to R.raw.dua02_part02_audio04,
                "عَلٰی اِبْرَاھِیْمَ" to R.raw.dua02_part02_audio05,
                "وَ بَارِکْ عَلٰی" to R.raw.dua02_part02_audio06,
                "مُحَمَّدٍ وَّعَلٰی" to R.raw.dua02_part02_audio07,
                "آلِ مُحَمَّدٍ" to R.raw.dua02_part02_audio08,
                "کَمَا بَارَکْتَ" to R.raw.dua02_part02_audio09,
                "عَلٰی اِبْرَاھِیْمَ" to R.raw.dua02_part02_audio10,
                "وَآلِ اِبْرَاھِیْمَ۔" to R.raw.dua02_part02_audio11
            )
        ),
        Dua(
            id = 5,
            arabic = "اَللّٰھُمَّ بِکَ اَصْبَحْنَا وَ بِکَ اَمْسَیْنَا وَ بِکَ نَحْیَا وَ بِکَ نَمُوْتُ  وَ اِلَيْكَ الْمَصِیْرُ",
            translation = "O Allah! By Your leave we reach the morning \n" +
                    "and by Your leave we reach the evening \n" +
                    "and by Your leave we live and by Your leave we die and to You is our return. ",
            reference = " [Sunan al-Tirmidhī]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua03_part01_audio01_complete,
            titleAudioResId = R.raw.title_morning,
            textheading = "Du’a of Morning\n" +
                    "(Before Sunrise)",
            image = R.drawable.dua_3,
            duaNumber = "3. ",
            wordAudioPairs = listOf(
                "اَللّٰھُمَّ بِکَ اَصْبَحْنَا" to R.raw.dua03_part01_audio01,
                "وَ بِکَ اَمْسَیْنَا" to R.raw.dua03_part01_audio02,
                "وَ بِکَ نَحْیَا" to R.raw.dua03_part01_audio03,
                "وَ بِکَ نَمُوْتُ" to R.raw.dua03_part01_audio04,
                "وَ اِلَيْكَ الْمَصِیْرُ" to R.raw.dua03_part01_audio05,
            )
        ),
        Dua(
            id = 6,
            arabic = "اَللّٰھُمَّ بِکَ اَمْسَیْنَا وَبِکَ اَصْبَحْنَا وَبِکَ نَحْیَا وَبِکَ نَمُوْتُ وَاِلَیْکَ النُّشُوْرُ۔ِ",
            translation = "O Allah! By Your leave we reach the evening and by Your leave we reach the morning and by Your leave we live and by Your leave we will die and to You is our resurrection.",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            reference = "[Sunan al-Tirmidhī]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            duaNumber = "4. ",
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua04_part01_audio01_complete,
            titleAudioResId = R.raw.title_evening,
            textheading = "Du’a of Evening\n" +
                    "(Before Sunset)",
            image = R.drawable.dua_4,
            wordAudioPairs = listOf(
                "اَللّٰھُمَّ بِکَ اَمْسَیْنَا" to R.raw.dua04_part01_audio01,
                "وَبِکَ اَصْبَحْنَا" to R.raw.dua04_part01_audio02,
                "وَبِکَ نَحْیَا" to R.raw.dua04_part01_audio03,
                "وَبِکَ نَمُوْتُ" to R.raw.dua04_part01_audio04,
                "وَاِلَیْکَ النُّشُوْرُ" to R.raw.dua04_part01_audio05,
            )
        ),
        Dua(
            id = 7,
            arabic = "اَعُوْذُ بِکَلِمَاتِ اللّٰہِ التَّامَّاتِ مِنْ شَرِّ مَا خَلَقَ۔",
            translation = "I seek refuge in the totality of the words of Allah from the evil of what He has created.",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            reference = "[Ṣaḥīḥ Muslim]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua05_part01_audio01_complete,
            titleAudioResId = R.raw.title_protection,
            textheading = " Du’a for Protection",
            duaNumber = "5. ",
            image = R.drawable.dua_5,
            wordAudioPairs = listOf(
                "اَعُوْذُ" to R.raw.dua05_part01_audio01,
                "بِکَلِمَاتِ اللّٰہِ التَّامَّاتِ" to R.raw.dua05_part01_audio02,
                "مِنْ شَرِّ" to R.raw.dua05_part01_audio03,
                "مَا خَلَقَ۔" to R.raw.dua05_part01_audio04,
            )
        ),
        Dua(
            id = 8,
            arabic = "بِسْمِ اللّٰہِ الَّذِیْ لَايَضُرُّ مَعَ اسْمِهِ شَىْءٌ فِى الْاَرْضِ وَلَا فِى السَّمَآءِ وَهُوَ السَّمِيعُ الْعَلِیْمُ",
            translation = "In the name of Allah, by Whose name nothing on the earth or in the heavens can cause harm,and He is the All Knowing, the All-Hearing. (3 times)",
            reference = "[Sunan Abu Dawud]",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua05_part02_audio01_complete,
            // titleAudioResId = R.raw.title_protection,
            image = R.drawable.dua_5,
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            duaNumber = "5. ",
         //  textheading = "Du’a for Protection",
            wordAudioPairs = listOf(
                "بِسْمِ اللّٰہِ الَّذِیْ" to R.raw.dua05_part02_audio01,
                "لَايَضُرُّ" to R.raw.dua05_part02_audio02,
                "مَعَ اسْمِهِ" to R.raw.dua05_part02_audio03,
                "شَىْءٌ فِى الْاَرْضِ" to R.raw.dua05_part02_audio04,
                "وَلَا فِى السَّمَآءِ" to R.raw.dua05_part02_audio05,
                "وَهُوَ السَّمِيعُ الْعَلِیْمُ" to R.raw.dua05_part02_audio06,
            )
        ),
        Dua(
            id = 9,
            arabic = "اَللّٰھُمَّ بِاسْمِكَ اَمُوْتُ وَاَحْیَا",
            translation = "O Allah! In your name I die and I live.",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            reference = "[Ṣaḥīḥ al-Bukhārī]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua06_part01_audio01_complete,
            titleAudioResId = R.raw.title_sleeping,
            image = R.drawable.dua_6,
            duaNumber = "6. ",
            textheading = " Du’a before Sleeping",
            steps = "1. Dust the bed before sleeping\n" +
                    "2. Sleep on the right side\n" +
                    "3. Put your hand under your right\ncheek and say",
            wordAudioPairs = listOf(
                "اَللّٰھُمَّ" to R.raw.dua06_part01_audio01,
                "بِاسْمِكَ" to R.raw.dua06_part01_audio02,
                "اَمُوْتُ" to R.raw.dua06_part01_audio03,
                "وَاَحْیَا" to R.raw.dua06_part01_audio04
            )
        ),
        Dua(
            id = 10,
            arabic = "اَلْـحَمْدُ لِلّٰهِ الَّذِیْ اَحْيَانَا بَعْدَ مَا اَمَاتَنَا وَاِلَيْهِ النُّشُوْرُ",
            translation = "All praise is for Allah ho gave us life after death (sleep) and to Him is the resurrection.",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            reference = "[Ṣaḥīḥ al-Bukhārī]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua07_part01_audio01_complete,
            titleAudioResId = R.raw.title_waking_up,
            image = R.drawable.dua_7,
            duaNumber = "7. ",
            textheading = " Du’a after Waking Up",
            steps = "Rub your face and your eyes with your hands to\n" +
                    "remove any remaining effects of sleep and say:",
            wordAudioPairs = listOf(
                "اَلْـحَمْدُ لِلّٰهِ الَّذِیْ" to R.raw.dua07_part01_audio01,
                "اَحْيَانَا" to R.raw.dua07_part01_audio02,
                "بَعْدَ مَا اَمَاتَنَا" to R.raw.dua07_part01_audio03,
                "وَاِلَيْهِ النُّشُوْرُ" to R.raw.dua07_part01_audio04,
            )
        ),
        Dua(
            id = 11,
            arabic = "اَللّٰھُمَّ اِنِّیْ اَعُوْذُبِکَ مِنَ الْخُبُثِ وَالْخَبَائِثِ",
            translation = "O Allah, I seek refuge in You from the impure male jinns and impure female jinns.",
            reference = "[Ṣaḥīḥ al-Bukhārī]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua08_part01_audio01_complete,
            titleAudioResId = R.raw.title_entering_toilet,
            textheading = " Du’a before Entering\nthe Toilet",
            image = R.drawable.dua_8,
            duaNumber = "8. ",
            steps = "Enter with your left foot and say:",
            wordAudioPairs = listOf(
                "اَللّٰھُمَّ اِنِّیْ اَعُوْذُبِکَ" to R.raw.dua08_part01_audio01,
                "مِنَ الْخُبُثِ" to R.raw.dua08_part01_audio02,
                "وَالْخَبَائِثِ" to R.raw.dua08_part01_audio03,
            )
        ),
        Dua(
            id = 12,
            arabic = "غُفْرَانَكَ",
            translation = "I ask you (Allah) for forgiveness.",
            reference = "[Sunan Abu Dawud]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua09_part01_audio01_complete,
            titleAudioResId = R.raw.title_leaving_toilet,
            image = R.drawable.dua_9,
            duaNumber = "9. ",
            textheading = " Du’a after Leaving \n" +
                    "the Toilet",
            steps = "Leave with your right foot and say:",
            wordAudioPairs = listOf(
                "غُفْرَانَكَ" to R.raw.dua09_part01_audio01,
            )
        ),
        Dua(
            id = 13,
            arabic = "اَلْحَمْدُ لِلّٰهِ الَّذِىْ كَسَانِى هٰذَا الثَّوْبَ وَرَزَقَنِيْهِ مِنْ غَيْرِحَوْلٍ مِّنِّى وَلَا قُوَّةٍ",
            translation = "All praise is for Allah Who has clothed me with this garment and provided it for me, with no power or might from myself. ",
            reference = "[Sunan Abu Dawūd]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua10_part01_audio01_complete,
            titleAudioResId = R.raw.title_before_putting_dress,
            duaNumber = "10. ",
            textheading = " Du’a before Putting\n" +
                    "on Dress",
            steps = "1. Shake and dust your dress before wearing.\n" +
                    "2. Start wearing the cloth from the right side (right\n" +
                    "sleeve, right side of the trouser, right socks, etc.).",
            image = R.drawable.dua_10,
            wordAudioPairs = listOf(
                "اَلْحَمْدُ لِلّٰهِ الَّذِىْ" to R.raw.dua10_part01_audio01,
                "كَسَانِى" to R.raw.dua10_part01_audio02,
                "هٰذَا الثَّوْبَ" to R.raw.dua10_part01_audio03,
                "وَرَزَقَنِيْهِ" to R.raw.dua10_part01_audio04,
                "مِنْ غَيْرِ" to R.raw.dua10_part01_audio05,
                "حَوْلٍ مِّنِّى" to R.raw.dua10_part01_audio06,
                "وَلَا قُوَّةٍ" to R.raw.dua10_part01_audio07,
            )
        ),
        Dua(
            id = 14,
            arabic = "بِسْمِ اللّٰہُِِِِ",
            translation = "In the Name of Allah.",
            reference = "[Sahih al-Jami’ al-Saghir]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua11_part01_audio01_complete,
            titleAudioResId = R.raw.title_taking_of_dress,
            image = R.drawable.dua_11,
            duaNumber = "11. ",
            steps = "Start to undress from the left side\n(left sleeve, left side of the trouser, left sock etc.",
            textheading = " Du’a before Taking \n" +
                    "off Dress",
            wordAudioPairs = listOf(
                "بِسْمِ اللّٰہِ" to R.raw.dua11_part01_audio01,
            )
        ),
        Dua(
            id = 15,
            arabic = "أَسْتَوْدِعُ اللَّهَ دِينَكَ وَأَمَانَتَكَ، وَخَوَاتِيمَ عَمَلِكَ",
            translation = "(I make) Allah responsible for your deen, your trustsworthiness and for the results of your actions",
            reference = "[Sunan al-Tirmidhi]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua12_part01_audio01_complete,
            titleAudioResId = R.raw.title_traveler,
            image = R.drawable.dua_15,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "12. ",
            textheading = " Du’a for Traveller",
            wordAudioPairs = listOf(
                "أَسْتَوْدِعُ اللّٰهَ" to R.raw.dua15_new_part01_audio01,
                "دِينَكَ" to R.raw.dua15_new_part01_audio02,
                "وَأَمَانَتَكَ،" to R.raw.dua15_new_part01_audio03,
                "وَخَوَاتِيمَ" to R.raw.dua15_new_part01_audio04,
                "عَمَلِكَ" to R.raw.dua15_new_part01_audio05,
            )
        ),
        Dua(
            id = 16,
            arabic = "بِسْمِ اللّٰہِ",
            translation = "In the Name of Allah ",
            reference = "[Ṣaḥīḥ Muslim] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua13_part01_audio01_complete,
            titleAudioResId = R.raw.title_entering_home,
            image = R.drawable.dua_13,
            duaNumber = "13. ",
            textheading = " Du’a while Entering\n" +
                    "the Home",
            wordAudioPairs = listOf(
                "بِسْمِ اللّٰہِ" to R.raw.dua13_part01_audio01,
            )
        ),
        Dua(
            id = 17,
            arabic = "اَلسَّلَامُ عَلَیْکُمْ",
            translation = "May Peace (of Allah) be upon you.",
            reference = "[Surah An-Nur: 27]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua13_part02_audio01_complete,
            //   titleAudioResId = R.raw.title_entering_home,
            image = R.drawable.dua_13,
            duaNumber = "13. ",
           // textheading = "Du’a while Entering\n" + "the Home",
            wordAudioPairs = listOf(
                "اَلسَّلَامُ عَلَیْکُمْ" to R.raw.dua13_part02_audio01,
            )
        ),
        Dua(
            id = 18,
            arabic = "اَللّٰهُمَّ إِنِّیْ أَعُوْذُبِکَ مِنْ مُنْکَرَاتِ الْأَخْلَاقِ، وَالْأَعْمَالِ، وَالْأَھْوَاءِ",
            translation = "O Allah! Verily, I seek refuge in You from bad manners, deeds and desires.",
            reference = "[Sunan al-Tirmidhī]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua14_part01_audio01_complete,
            titleAudioResId = R.raw.title_bad_ikhlaq,
            image = R.drawable.dua_14,
            duaNumber = "14. ",
            textheading = " Du’a for protection\n" +
                    "from Bad Akhlaq",
            wordAudioPairs = listOf(
                "اَللّٰهُمَّ إِنِّیْ أَعُوْذُبِکَ" to R.raw.dua14_part01_audio01,
                "مِنْ مُنْکَرَاتِ الْأَخْلَاقِ،" to R.raw.dua14_part01_audio02,
                "وَالْأَعْمَالِ،" to R.raw.dua14_part01_audio03,
                "وَالْأَھْوَاءِ" to R.raw.dua14_part01_audio04,
            )
        ),
        Dua(
            id = 19,
            arabic = "بِسْمِ اللّٰہِ",
            translation = "In the Name of Allah.",
            reference = " [Sunan Abu Dawūd]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua15_part01_audio01_complete,
            titleAudioResId = R.raw.title_journey,
            image = R.drawable.dua_16,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "15. ",
            textheading = " Du’a for Journey",
            wordAudioPairs = listOf(
                "بِسْمِ اللّٰہِ" to R.raw.dua15_part01_audio01,
            )
        ),
        Dua(
            id = 20,
            arabic = "اَلْحَمْدُ لِلّٰہِ",
            translation = "All Praise is for Allah.",
            reference = " [Sunan Abu Dawūd]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua15_part02_audio01_complete,
            // titleAudioResId = R.raw.title_journey,
            image = R.drawable.dua_16,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "15. ",
          //  textheading = "Du’a for Journey",
            wordAudioPairs = listOf(
                "اَلْحَمْدُ لِلّٰہ" to R.raw.dua15_part02_audio01,
            )
        ),
        Dua(
            id = 21,
            arabic = "سُبْحٰنَ الَّذِیْ سَخَّرَلَنَا ھٰذَا وَمَاکُنَّا لَہ مُقْرِنِیْنَoوَاِنَّآ اِلٰی رَبِّنَا لَمُنْقَلِبُوْنَo",
            translation = "Glory to Him Who created this transportation for us, though we were unable to create it on our own. And to our Lord we shall return.",
            reference = " [al-Zukhruf: 13-14]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua15_part03_audio01_complete,
            // titleAudioResId = R.raw.title_journey,
            image = R.drawable.dua_16,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "15. ",
           // textheading = "Du’a for Journey",
            wordAudioPairs = listOf(
                "سُبْحٰنَ الَّذِیْ" to R.raw.dua15_part03_audio01,
                "سَخَّرَلَنَا" to R.raw.dua15_part03_audio02,
                "ھٰذَا" to R.raw.dua15_part03_audio04,
                "وَمَاکُنَّا" to R.raw.dua15_part03_audio05,
                "لَہ مُقْرِنِیْنَo" to R.raw.dua15_part03_audio06,
                "وَاِنَّآ اِلٰی" to R.raw.dua15_part03_audio07,
                "رَبِّنَا" to R.raw.dua15_part03_audio08,
                "لَمُنْقَلِبُوْنَo" to R.raw.dua15_part03_audio09,
            )
        ),
        Dua(
            id = 22,
            arabic = "اَلسَّلَامُ عَلَیْکُمْ وَرَحْمَةُ اللّٰہِ وَ بَرَکَاتُہُِِ",
            translation = "May peace, mercy and blessings (of Allah) be upon You.",
            reference = "[Sunan Abu Dawūd]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua16_part01_audio01_complete,
            titleAudioResId = R.raw.title_meeting_muslim,
            image = R.drawable.dua_17,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "16. ",
            textheading = " Du’a When Meeting\n" +
                    "a Muslim",
            wordAudioPairs = listOf(
                "اَلسَّلَامُ عَلَیْکُمْ وَرَحْمَةُ اللّٰہِ وَ بَرَکَاتُہُ" to R.raw.dua16_part01_audio01

            )
        ),
        Dua(
            id = 23,
            arabic = "وَعَلَیْکُمُ السَّلَامُ وَ رَ حْمَةُ اللّٰہِ وَ بَرَکَاتُہُُِِ",
            translation = "May peace, mercy and blessings of Allah be upon You as Well.",
            reference = "[Sunan Abu Dawūd]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua16_part02_audio01_complete,
            // titleAudioResId = R.raw.title_meeting_muslim,
            image = R.drawable.dua_17,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "16. ",
            steps = "Reply to the Greeting:",
          //  textheading = "Du’a When Meeting\n" + "a Muslim",
            wordAudioPairs = listOf(
                "وَعَلَیْکُمُ السَّلَامُ وَرَحْمَةُ اللّٰہِ وَبَرَکَاتُہُ" to R.raw.dua16_part02_audio01
            )
        ),


        Dua(
            id = 24,
            arabic = "سُبْحَانَكَ اللّٰھُمَّ وَبِحَمْدِکَ،اَشْھَدُاَنْ لَّااِلٰہَ اِلَّااَنْتَ، اَسْتَغْفِرُکَ وَاَتُوْبُ اِلَیْکَ",
            translation = "Glory be to You O Allah, and all praise be to You! I bear witness that there is no true deity except You, I seek Your forgiveness and turn in repentance to You.",
            reference = " [Sunan Abu Dawūd]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua17_part01_audio01_complete,
            titleAudioResId = R.raw.title_gathering,
            image = R.drawable.dua_18,
            duaNumber = "17. ",
            textheading = " Du’a at the End of a\n" + "Gathering",
            wordAudioPairs = listOf(
                "سُبْحَانَكَ اللّٰھُمَّ وَبِحَمْدِکَ،" to R.raw.dua17_part01_audio01,
                "اَشْھَدُاَنْ لَّااِلٰہَ اِلَّااَنْتَ،" to R.raw.dua17_part01_audio02,
                "اَسْتَغْفِرُکَ وَاَتُوْبُ اِلَیْکَ" to R.raw.dua17_part01_audio03,
            )
        ),
        Dua(
            id = 25,
            arabic = "لَا اِلٰہَ اِلَّا اللّٰہُ وَحْدَہٗ  لَا شَرِیْکَ لَهٗ،لَہُ الْمُلْکُ وَلَہُ الْحَمْدُ یُحْیِی وَ یُمِیْتُ وَھُوَ حَیٌّ لَّا یَمُوْتُ بِیَدِہِ الْخَیْرُ وَھُوَ عَلٰی کُلِّ شَىْءٍ قَدِیْرٌ",
            translation = "There is no true deity except Allah, alone, He has no partners. To Him belongs the dominion and for Him is all praise. He gives life and causes death,  and He is living and does not die. In His hand is all good and He is upon all things always All-Powerful.",
            reference = "[Sunan al-Tirmidhi]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua18_part01_audio01_complete,
            titleAudioResId = R.raw.title_market,
            image = R.drawable.dua_19,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "18. ",
            textheading = " Du’a When Entering the\n" + "Market",
            wordAudioPairs = listOf(
                "لَا اِلٰہَ اِلَّا اللّٰہُ" to R.raw.dua18_part01_audio01,
                "وَحْدَہٗ لَا شَرِیْکَ لَهٗ،" to R.raw.dua18_part01_audio02,
                "لَہُ الْمُلْکُ" to R.raw.dua18_part01_audio03,
                "وَلَہُ الْحَمْدُ" to R.raw.dua18_part01_audio04,
                "یُحْیِی" to R.raw.dua18_part01_audio05,
                "وَ یُمِیْتُ" to R.raw.dua18_part01_audio06,
                "وَھُوَ حَیٌّ لَّا یَمُوْتُ" to R.raw.dua18_part01_audio07,
                "بِیَدِہِ الْخَیْرُ" to R.raw.dua18_part01_audio08,
                "وَھُوَ عَلٰی کُلِّ شَىْءٍ قَدِیْرٌ" to R.raw.dua18_part01_audio09,
            )
        ),
        Dua(
            id = 26,
            arabic = "اَللّٰھُمَّ افْتَحْ لِیْ اَبْوَابَ رَحْمَتِکَُُِِ",
            translation = "O Allah, open for me the doors of your mercy.",
            reference = "[Sunan al-Nasa’i]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua19_part01_audio01_complete,
            titleAudioResId = R.raw.title_entering_masjid,
            image = R.drawable.dua_20,
            duaNumber = "19. ",
            steps = "Enter the Masjid with the right foot and say:",
            textheading = " Du’a When Entering\nthe Masjid",
            wordAudioPairs = listOf(
                "اَللّٰھُمَّ افْتَحْ لِیْ" to R.raw.dua19_part01_audio01,
                "اَبْوَابَ رَحْمَتِکَ" to R.raw.dua19_part01_audio02,
            )
        ),
        Dua(
            id = 27,
            arabic = "اَللّٰھُمَّ اِنِّی اَسْئَلُکَ مِنْ فَضْلِکََُُِِ",
            translation = "O Allah, I ask you of Your bounties.",
            reference = " [Sahih Muslim]",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua20_part01_audio01_complete,
            titleAudioResId = R.raw.title_leaving_masjid,
            image = R.drawable.dua_21,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "20. ",
            steps = "Leave the masjid with the left foot and say:",
            textheading = " Du’a When Leaving\n" +
                    "the Masjid",
            wordAudioPairs = listOf(
                "اَللّٰھُمَّ اِنِّی اَسْئَلُکَ" to R.raw.dua20_part01_audio01,
                "مِنْ فَضْلِکَ" to R.raw.dua20_part01_audio02,
            )
        ),
        Dua(
            id = 28,
            arabic = "بِسْمِ اللّٰہَُُِِِ",
            translation = "In the Name of Allah.",
            reference = "  [Sunan Ibn Majah] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua21_part01_audio01_complete,
            titleAudioResId = R.raw.title_eating_drinking,
            image = R.drawable.dua_22,
            duaNumber = "21. ",
            steps = "1. Sit while eating and drinking\n" + "2. Eat with your right hand and eat from\n" + "what is in front of you and say:",
            textheading = " Du’a Before Eating\n& Drinking",
            wordAudioPairs = listOf(
                "بِسْمِ اللّٰہِ" to R.raw.dua21_part01_audio01,
            )
        ),
        Dua(
            id = 29,
            arabic = "بِسْمِ اللّٰہِ فِی اَوَّلِہِ وَآخِرِہِ",
            translation = "In the name of Allah, at the beginning and\n" + "at the end.",
            reference = "  [Sunan Ibn Majah] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua21_part02_audio01_complete,
            //  titleAudioResId = R.raw.title_eating_drinking,
            image = R.drawable.dua_22,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "21. ",
            steps = "3. If you forgot to read the Du'a at the beginning\n" + "then upon remembering say:",
          //  textheading = "Du’a Before Eating\n& Drinking",
            wordAudioPairs = listOf(
                "بِسْمِ اللّٰہِ" to R.raw.dua21_part02_audio01,
                "فِی اَوَّلِہِ" to R.raw.dua21_part02_audio02,
                "وَآخِرِہِ" to R.raw.dua21_part02_audio03,
            )
        ),
        Dua(
            id = 30,
            arabic = "اَلّٰھُمَّ بَارِکْ لَناَ فِیْہِ وَاَطْعِمْنَا خَیْرًا مِّنْہُ",
            translation = "O Allah, You grant us blessings in it and \n" +
                    "grant us better than it.",
            reference = "[Sunan al-Tirmidhi] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua22_part01_audio01_complete,
            titleAudioResId = R.raw.title_after_eating,
            image = R.drawable.dua_23,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "22. ",
            textheading = " Du’a after Eating\n& Drinking",
            wordAudioPairs = listOf(
                "اَلّٰھُمَّ بَارِکْ لَناَ فِیْہِ" to R.raw.dua22_part01_audio01,
                "وَاَطْعِمْنَا" to R.raw.dua22_part01_audio02,
                "خَیْرًا مِّنْہُ" to R.raw.dua22_part01_audio03,
            )
        ),
        Dua(
            id = 31,
            arabic = "لَا بَأْسَ طَهُورٌ إِنْ شَاءَ اللَّهَُُُُِِِ",
            translation = "No harm, (this illness will be) a purification (from\n" + "sins), if Allah wills.",
            reference = " [Sahih al-Bukhari]  ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua23_part01_audio01_complete,
            titleAudioResId = R.raw.title_sick,
            image = R.drawable.dua_24,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "23. ",
            textheading = " Du’a When Visiting\n" +
                    "the Sick",
            wordAudioPairs = listOf(
                "لَا بَأْسَ" to R.raw.dua24_part01_audio01,
                "طَهُورٌ" to R.raw.dua24_part01_audio02,
                "إِنْ شَاءَ اللَّهُ" to R.raw.dua24_part01_audio03,
            )
        ),
        Dua(
            id = 32,
            arabic = "اَسْاَلُ اللّٰہَ الْعَظِیْمَ رَبَّ الْعَرْشِ الْعَظِیْمِ اَنْ یَّشْفِیَکَ",
            translation = "I ask Allah, the Great, Lord of the Magnificent\n" + "Throne, to cure you.",
            reference = "[Sunan al-Tirmidhi ] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua23_part02_audio01_complete,
            // titleAudioResId = R.raw.title_sick,
            image = R.drawable.dua_24,
            duaNumber = "23. ",
           // textheading = "Du’a When Visiting\n" + "the Sick",
            wordAudioPairs = listOf(
                "اَسْاَلُ اللّٰہَ الْعَظِیْمَ" to R.raw.dua24_part02_audio01,
                "رَبَّ الْعَرْشِ الْعَظِیْمِ" to R.raw.dua24_part02_audio02,
                "اَنْ یَّشْفِیَکَ" to R.raw.dua24_part02_audio03,
            )
        ),
        Dua(
            id = 33,
            arabic = "اِنَّا لِلّٰہِ وَاِنَّا اِلَیْہِ رَاجِعُوْنَ، \u2028اَللّٰھُمَّ اْجُرْنِىْ فِىْ مُصِیْبَتِیْ وَاَخْلِفْ لِىْ خَيْرًا مِّنْهَا",
            translation = "Indeed we belong to Allah, and indeed to Him we will return. O Allah, recompense me for my affliction and replace it for me with something better.",
            reference = "[Sahih Muslim]  ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua24_part01_audio01_complete,
            titleAudioResId = R.raw.title_calamity,
            image = R.drawable.dua_25,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "24. ",
            textheading = " Du’a for one Afflicted\nby a Calamity",
            wordAudioPairs = listOf(
                "اِنَّا لِلّٰہِ" to R.raw.dua25_part01_audio01,
                "وَاِنَّا اِلَیْہِ" to R.raw.dua25_part01_audio02,
                "رَاجِعُوْنَ،" to R.raw.dua25_part01_audio03,
                "اَللّٰھُمَّ اْجُرْنِىْ" to R.raw.dua25_part01_audio04,
                "فِىْ مُصِیْبَتِیْ" to R.raw.dua25_part01_audio05,
                "وَاَخْلِفْ لِىْ" to R.raw.dua25_part01_audio06,
                "خَيْرًا مِّنْهَا" to R.raw.dua25_part01_audio07
            )
        ),
        Dua(
            id = 34,
            arabic = "اَلْحَمْدُ لِلّٰهِ  الَّذِی عَافَانِی  مِمَّا ابْتَلَاکَ بِهِ وَ فَضَّلَنِی  عَلٰی کَثِیْرٍ مِمَّنْ خَلَقَ  تَفْضِيْلًا",
            translation = "All praise is for Allah, Who saved me from that\n" +
                    "which He tested you with and favoured me over\n" + "much of His creation.",
            reference = "[Sunan al-Tirmidhi] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua25_part01_audio01_complete,
            titleAudioResId = R.raw.title_seeing_in_calamity,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "25. ",
            image = R.drawable.dua_26,
            textheading = " Du’a upon Seeing Someone\nin Calamity ",
            wordAudioPairs = listOf(
                "اَلْحَمْدُ لِلّٰهِ الَّذِی" to R.raw.dua26_part01_audio01,
                "عَافَانِی" to R.raw.dua26_part01_audio02,
                "مِمَّا ابْتَلَاکَ" to R.raw.dua26_part01_audio03,
                "بِهِ" to R.raw.dua26_part01_audio04,
                "وَ فَضَّلَنِی" to R.raw.dua26_part01_audio05,
                "عَلٰی کَثِیْرٍ" to R.raw.dua26_part01_audio06,
                "مِمَّنْ خَلَقَ" to R.raw.dua26_part01_audio07,
                "تَفْضِيْلًا" to R.raw.dua26_part01_audio08
            )
        ),
        Dua(
            id = 35,
            arabic = "اَعُوْذُ بِاللّٰہِ مِنَ الشَّیْطَانِ الرَّجِیْمِ",
            translation = "I seek refuge in Allah from the Satan the rejected.",
            reference = " [Sahih al-Bukhari] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua26_part01_audio01_complete,
            titleAudioResId = R.raw.title_angry,
            image = R.drawable.dua_27,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "26. ",
            steps = "Seek refuge with Allah from the Satan: ",
            textheading = " Du’a when Angry",
            wordAudioPairs = listOf(
                "اَعُوْذُ بِاللّٰہِ" to R.raw.dua27_part01_audio01,
                "مِنَ الشَّیْطَانِ الرَّجِیْمِ" to R.raw.dua27_part01_audio02,
            )
        ),
        Dua(
            id = 36,
            arabic = "اَلْحَمْدُ لِلّٰہِ",
            translation = "All praises to Allah.",
            reference = " [Sahih al-Bukhari] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua27_part01_audio01_complete,
            titleAudioResId = R.raw.title_sneezing,
            image = R.drawable.dua_28,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "27. ",
            steps = "Say after sneezing: ",
            textheading = " Du’a when Sneezing",
            wordAudioPairs = listOf(
                "اَلْحَمْدُ لِلّٰہِ" to R.raw.dua28_part01_audio01,
            )
        ),
        Dua(
            id = 37,
            arabic = "یَرْحَمُکَ اللّٰہُ",
            translation = "May Allah have mercy on you.",
            reference = " [Sahih al-Bukhari] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua27_part02_audio01_complete,
            // titleAudioResId = R.raw.title_sneezing,
            image = R.drawable.dua_28,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "27. ",
            steps = "Dua by one who hears someone saying اَلْحَمْدُ لِلّٰہِ",
          //  textheading = "Du‘a when Sneezing",
            wordAudioPairs = listOf(
                "یَرْحَمُکَ اللّٰہُ" to R.raw.dua28_part02_audio01,
            )
        ),
        Dua(
            id = 38,
            arabic = "یَھْدِیْکُمُ اللّٰہُ وَیُصْلِحُ بَالَکُمْ",
            translation = "May Allah guide you and improve your position.",
            reference = " [Sahih al-Bukhari] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua27_part03_audio01_complete,
            //  titleAudioResId = R.raw.title_sneezing,
            duaNumber = "27. ",
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            image = R.drawable.dua_28,
            steps = "Du’a in reply by the person who sneezes:",
          //  textheading = "Du‘a when Sneezing",
            wordAudioPairs = listOf(
                "یَھْدِیْکُمُ اللّٰہُ" to R.raw.dua28_part03_audio01,
                "وَیُصْلِحُ بَالَکُمْ" to R.raw.dua28_part03_audio02,
            )
        ),
        Dua(
            id = 39,
            arabic = "اَلّٰھُمَّ اجْعَلْہُ  صَیِّباً  نَافِعاً",
            translation = "O Allah, may it be a beneficial rain cloud.",
            reference = "[Sunan al-Nasa’i]  ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua28_part01_audio01_complete,
            titleAudioResId = R.raw.title_rains,
            image = R.drawable.dua_29,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "28. ",
            textheading = " Du’a when it Rains",
            wordAudioPairs = listOf(
                "اَلّٰھُمَّ اجْعَلْہُ" to R.raw.dua29_part01_audio01,
                "صَیِّباً نَافِعاً" to R.raw.dua29_part01_audio02,
            )
        ),
        Dua(
            id = 40,
            arabic = "اَلّٰھُمَّ اَھْلِلْہُ عَلَیْنَا بِلْیُمْنِ وَالْاِیْمَانِ وَالسَّلَامَةِ وَالْاِسْلَامِ رَبِّیْ وَرَبُّکَ اللّٰہُ",
            translation = "O Allah! Let the moon appear over us with\n" + "security, faith, peace and Islam. [O moon!] My\n" + "Lord and your Lord is Allah. ",
            reference = "[Sunan al-Tirmidhi] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua29_part01_audio01_complete,
            titleAudioResId = R.raw.title_moon,
            image = R.drawable.dua_30,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "29. ",
            textheading = "Du’a upon Sighting\nthe Crescent Moon",
            wordAudioPairs = listOf(
                "اَلّٰھُمَّ اَھْلِلْہُ عَلَیْنَا" to R.raw.dua30_part01_audio01,
                "بِلْیُمْنِ" to R.raw.dua30_part01_audio03,
                "وَالْاِیْمَانِ" to R.raw.dua30_part01_audio04,
                "وَالسَّلَامَةِ" to R.raw.dua30_part01_audio05,
                "وَالْاِسْلَامِ" to R.raw.dua30_part01_audio06,
                "رَبِّیْ وَرَبُّکَ اللّٰہُ" to R.raw.dua30_part01_audio07,
            )
        ),
        Dua(
            id = 41,
            arabic = "اللَّهُمَّ إِنِّي أَسْأَلُكَ حُبَّكَ  وَحُبَّ مَنْ يُحِبُّكَ  وَعَمَلٍ يُقَرِّبُنِي إِلَى حُبِّكَ",
            translation = "O Allah! I ask You for Your love and for the love of\n" + "the one who loves You and I ask for the deeds\n" + "which lead me towards Your love.",
            reference = "[Sunan al-Tirmidhi] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua30_part01_audio01_complete,
            titleAudioResId = R.raw.title_seeking_love,
            image = R.drawable.dua_31,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "30. ",
            textheading = " Du’a for Seeking\nAllah’s Love",
            wordAudioPairs = listOf(
                "اَلّٰھُمَّ اِنِّیْ اَسْاَلُكَ" to R.raw.dua31_part01_audio01,
                "حُبَّكَ" to R.raw.dua31_part01_audio02,
                "وَحُبَّ" to R.raw.dua31_part01_audio03,
                "مَنْ يُّحِبُّكَ" to R.raw.dua31_part01_audio04,
                "وَعَمَلٍ يُّقَرِّبُنِي" to R.raw.dua31_part01_audio05,
                "اِلَى حُبِّكَ" to R.raw.dua31_part01_audio06,
            )
        ),
        Dua(
            id = 42,
            arabic = "اَللّٰھُمَّ اَنْتَ رَبِّى،لَا اِلٰہَ اِلَّااَنْتَ ،خَلَقْتَنِیْ وَاَنَا عَبْدُکَ وَاَنَا عَلَی عَھْدِکَ وَوَعْدِکَ مَااسْتَطَعْتُ،\u2028اَعُوْذُبِکَ مِنْ شَرِّ مَاصَنَعْتُ، اَبُوْءُلَکَ بِنِعْمَتِکَ عَلَیَّ وَاَبُوْءُ بِذَنْبِی فَاغْفِرْلِیْ  فَاِنَّهُ لَا یَغْفِرُالذُّنُوْبَ اِلَّا اَنْتَ",
            translation = "O Allah, You are my Lord; there is no deity worthy\n" + "of worship except You. You created me and I am\n" + "your servant, I abide by Your covenant and\n" + "promise to the best of my ability. I seek refuge \n" +
                    "with You from the evil of which I have committed. \n" +
                    "I acknowledge Your blessings upon me and I\n" + "acknowledge my sin, so forgive me, for verily\n" + "none forgives sins except You. ",
            reference = "[Sahih al-Bukhari] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua31_part01_audio01_complete,
            titleAudioResId = R.raw.title_istighfar,
            image = R.drawable.dua_32,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "31. ",
            textheading = " Du’a:Sayyid-ul-Istighfar ",
            wordAudioPairs = listOf(
                "اَللّٰھُمَّ اَنْتَ رَبِّى،" to R.raw.dua32_part01_audio01,
                "لَا اِلٰہَ " to R.raw.dua32_part01_audio02,
                "اِلَّااَنْتَ" to R.raw.dua32_part01_audio03,
                "،خَلَقْتَنِیْ" to R.raw.dua32_part01_audio04,
                "وَاَنَا عَبْدُکَ" to R.raw.dua32_part01_audio05,
                "وَاَنَا عَلَی عَھْدِکَ" to R.raw.dua32_part01_audio06,
                "وَوَعْدِکَ" to R.raw.dua32_part01_audio07,
                "مَااسْتَطَعْتُ،" to R.raw.dua32_part01_audio08,
                "اَعُوْذُبِکَ" to R.raw.dua32_part01_audio09,
                "مِنْ شَرِّ" to R.raw.dua32_part01_audio10,
                "مَاصَنَعْتُ،" to R.raw.dua32_part01_audio11,
                "اَبُوْءُلَکَ" to R.raw.dua32_part01_audio12,
                "بِنِعْمَتِکَ" to R.raw.dua32_part01_audio13,
                "عَلَیَّ" to R.raw.dua32_part01_audio14,
                "وَاَبُوْءُ" to R.raw.dua32_part01_audio15,
                "بِذَنْبِی" to R.raw.dua32_part01_audio16,
                "فَاغْفِرْلِیْ" to R.raw.dua32_part01_audio17,
                "فَاِنَّهُ" to R.raw.dua32_part01_audio18,
                "لَا یَغْفِرُالذُّنُوْبَ" to R.raw.dua32_part01_audio19,
                "اِلَّا اَنْتَ" to R.raw.dua32_part01_audio20
            )

        ),
        Dua(
            id = 43,
            arabic = "اَعُوْذُ بِوَجْهِ اللّٰہِ الْعَظِیْمِ الَّذِیْ لَیْسَ شَیْءٌ اَعْظَمَ مِنْهُ وَبِكَلِمَاتِ اللّٰہِ التَّامَّاتِ الَّتِیْ لَا يُجَاوِزُهُنَّ بَرٌّ وَّلَا فَاجِرٌ وَبِاَسْمَاءِ اللّٰہِ الْحُسْنٰى كُلِّهَا مَا عَلِمْتُ مِنْهَا وَمَا لَمْ اَعْلَمْ مِنْ شَرِّ مَا خَلَقَ وَبَرَاَ وَذَرَاَ",
            translation = "I seek refuge with the immense Face of Allah -\n" +
                    "there is nothing greater than it - and with the \n" + "complete words of Allah which neither the good\n" + "person nor the corrupt can exceed and with all\n" + "the most beautiful names of Allah, what I know of\n" + "them and what I do not know, from the evil of\n" + "what He has created and originated and multiplied.",
            reference = "[Mishkat ul-Masabih] ",
            urdu = "اے اللہ تیرے حکم سے ہم نے صبح کی اور تیرے حکم سے ہم شام کو پہنچے اور تیرے حکم سے ہم جیتے اور مرتے ہیں اور تیری ہی طرف لوٹ کر جانا ہے۔",
            backgroundResId = R.drawable.header_bg,
            statusBarColorResId = R.color.top_nav_new,
            fullAudioResId = R.raw.dua32_part01_audio01_complete,
            titleAudioResId = R.raw.title_refuse_with_allah,
            image = R.drawable.dua_33,
            hinditranslation = "ऐ अल्लाह, तेरी ही आज्ञा से हम सुबह तक पहुँचे हैं और तेरी ही आज्ञा से हम शाम तक पहुँचे हैं और तेरी ही आज्ञा से हम जीते हैं और मरते हैं, और तेरी ही ओर हमें लौटना है।",
            duaNumber = "32. ",
            textheading = " Seeking Refuge\nwith Allah",
            wordAudioPairs = listOf(
                "اَعُوْذُ" to R.raw.dua33_part01_audio01,
                "بِوَجْهِ اللّٰہِ الْعَظِیْمِ الَّذِیْ" to R.raw.dua33_part01_audio02,
                "لَیْسَ شَیْءٌ" to R.raw.dua33_part01_audio03,
                "اَعْظَمَ مِنْهُ" to R.raw.dua33_part01_audio04,
                "وَبِكَلِمَاتِ اللّٰہِ التَّامَّاتِ الَّتِیْ" to R.raw.dua33_part01_audio05,
                "لَا يُجَاوِزُهُنَّ" to R.raw.dua33_part01_audio06,
                "بَرٌّ وَّلَا فَاجِرٌ" to R.raw.dua33_part01_audio08,
                "وَبِاَسْمَاءِاللّٰہِ الْحُسْنٰى" to R.raw.dua33_part01_audio09,
                "كُلِّهَا" to R.raw.dua33_part01_audio10,
                "مَا عَلِمْتُ مِنْهَا" to R.raw.dua33_part01_audio11,
                "وَمَا لَمْ اَعْلَمْ" to R.raw.dua33_part01_audio12,
                "مِنْ شَرِّ مَا" to R.raw.dua33_part01_audio13,
                "خَلَقَ" to R.raw.dua33_part01_audio14,
                "وَبَرَاَ وَذَرَاَ" to R.raw.dua33_part01_audio15
            )
        ),
    )
}
